[variables]
PYTHONUNBUFFERED = "1"

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python3 -m uvicorn backend.app:app --host 0.0.0.0 --port $PORT"
